#!/bin/sh
check_result () {
	echo "Return is $1"
	if [ "$1" == "2" ]; then
		echo 1 > /tmp/result
		exit 1
	fi
}

. ../../Utils/SourceMe
make -j32 LOADADDR=0x10008000 uImage 
make modules
make imx6q-GDS-novasom.dtb

pushd ../../Deploy
ln -s ../Kernel/linux-3.10.17_1.0.2_ga-NOVAsom6/arch/arm/boot/dts/imx6q-GDS-novasom.dtb
popd

